alias: '[Computers] Restart RPI3 when offline'
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: device_tracker.alarm_rpi
  to: away
action:
- service: switch.turn_off
  data:
    entity_id:
      - switch.rasbperrypi3
- delay: 00:00:30
- service: switch.turn_on
  data:
    entity_id:
      - switch.rasbperrypi3
