alias: "[Light on] Toilet Door lights on"
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: binary_sensor.toilet_door
  to: 'on'
action:
- service: homeassistant.turn_on
  data:
    entity_id: light.toilet
- service: timer.cancel
  data:
    entity_id: timer.toilet
- service: timer.start
  data:
    entity_id: timer.toilet
