alias: "[Light on] Noan LED on motion"
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: binary_sensor.noan_motion
  to: 'on'
- platform: state
  entity_id: binary_sensor.noan_door
  to: 'on'
condition:
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 8
action:
- service: homeassistant.turn_on
  data:
    entity_id: light.nowen
- service: timer.cancel
  data:
    entity_id: timer.noan
- service: timer.start
  data:
    entity_id: timer.noan
