alias: "[Light on] Bathroom motion lights on"
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: binary_sensor.bathroom
  to: 'on'
- platform: state
  entity_id: binary_sensor.bathroom_door
  to: 'on'
condition:
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 8
action:
- service: homeassistant.turn_on
  data:
    entity_id: light.night_old
- service: timer.cancel
  data:
    entity_id: timer.bathroom
- service: timer.start
  data:
    entity_id: timer.bathroom
