alias: "[Light off] Nightlight LED off"
hide_entity: false
initial_state: 'on'
trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.nightlight
action:
- service: homeassistant.turn_off
  data:
    entity_id:
      - light.night_light_2
