alias: "[Light off] IT room desktop off, lights off"
hide_entity: false
initial_state: 'false'
trigger:
  - platform: state
    entity_id: switch.desktop
    to: 'off'
    for:
      minutes: 5
action:
  - service: homeassistant.turn_off
    data:
      entity_id:
        - switch.desk
        - light.it_room_light
        - light.desk_light
        - switch.desk_second
  - service: input_boolean.turn_off
    data:
      entity_id:
        - input_boolean.pioneer     