alias: '[Alarm clock] snooze action'
initial_state: 'on'
hide_entity: true
trigger:
- platform: event
  event_type: ios.notification_action_fired
  event_data:
    actionName: SNOOZE
action:
  service: script.turn_on
  entity_id: script.alarm_clock_snooze_button
