alias: "[Light off] Jade LED off"
hide_entity: false
initial_state: 'on'
trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.jade
action:
- service: light.turn_off
  data:
    entity_id:
      - light.jade
