alias: "[Ring] Alexa Front Doorbell Notification"
hide_entity: false
initial_state: 'on'
trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_ding
    from: 'off'
    to: 'on'
action:
  service: media_player.alexa_tts
  data:
    entity_id: media_player.it_room, media_player.kitchen, media_player.livingroom, media_player.bedroom, media_player.matthews_sonos_beam
    message: “Someone is at the front door”
