alias: '[Alarm] Alexa guard off'
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: alarm_control_panel.house
  to: 'disarmed'
- platform: state
  entity_id: alarm_control_panel.house
  to: 'armed_home'  
action:
- service: alarm_control_panel.alarm_disarm
  entity_id: alarm_control_panel.alexa_guard_6fd20
