alias: '[Alarm] Auto Disarm Alarm when home'
hide_entity: false
initial_state: 'off'
trigger:
  - platform: state
    entity_id: person.ezra
    to: home
condition:
  - condition: state
    entity_id: alarm_control_panel.house
    state: 'armed_away'
action:
- service: alarm_control_panel.alarm_disarm
  entity_id: alarm_control_panel.house
  data:
    code: !secret alarm
