alias: Ezra [BLE] device tracker On
initial_state: 'on'
hide_entity: false
trigger:
  - platform: numeric_state
    entity_id: sensor.ezra_occupancy_confidence_ble
    above: 10
action:
  - service: device_tracker.see
    data:
      dev_id: geheime_dienst
      location_name: home
      source_type: bluetooth
