alias: "[Light on] Bed led on bed presence on"
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: binary_sensor.ezra_bed_presence
  to: 'off'
condition:
  condition: and
  conditions:
    - condition: time
      after: '21:00:00'
      before: '06:00:00'
    - condition: state
      entity_id: person.ezra
      state: 'home'
action:
- delay: 00:00:05
- service: homeassistant.turn_on
  data:
    entity_id: switch.bedroom_led
    brightness: 26
    xy_color: [0.701, 0.299]
