alias: '[Charger] Bedroom on'
hide_entity: false
initial_state: 'on'
trigger:
  platform: time
  at: '21:00:00'
condition:
  - condition: state
    entity_id: 'person.ezra'
    state: 'home'
action:
  - service: switch.turn_on
    data:
      entity_id:
        - switch.bedroom_charger
