alias: "[Curtain] Open curtains [Ezra] based on SUN"
hide_entity: false
initial_state: 'on'
trigger:
  platform: state
  entity_id: binary_sensor.ezra_bed_presence
  to: 'off'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: person.ezra
      state: 'home'
    - condition: state
      entity_id: input_boolean.curtain_ezra
      state: 'on'
    - condition: time
      after: '04:45:00'
      before: '09:00:00'      
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.curtain_ezra