alias: '[Light on] Kitchen motion lights on'
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: binary_sensor.kitchen_motion
  to: 'on'
- platform: state
  entity_id: binary_sensor.kitchen_2
  to: 'on'
condition:
- condition: numeric_state
  entity_id: sun.sun
  value_template: '{{ state.attributes.elevation }}'
  below: 8
action:
- service: homeassistant.turn_on
  data:
    entity_id: light.kitchen
- service: timer.cancel
  data:
    entity_id: timer.kitchen
- service: timer.start
  data:
    entity_id: timer.kitchen
