alias: "[Light off] Kitchen off"
hide_entity: false
initial_state: 'on'
trigger:
  platform: event
  event_type: timer.finished
  event_data:
    entity_id: timer.kitchen
action:
- service: homeassistant.turn_off
  data:
    entity_id:
      - light.kitchen
