alias: Indirect Bedroom LED 1/4
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: switch.bedroom_led
  from: 'off'
  to: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: light.bled
