alias: Indirect Bedroom Lights 4/4
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: group.bedroom
  from: 'on'
  to: 'off'
action:
  - service: homeassistant.turn_off
    entity_id: switch.bedroom_lights
