alias: Indirect Bedroom Lights 1/4
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: switch.bedroom_lights
  from: 'off'
  to: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: group.bedroom
