alias: "[Curtain] Ezra boolean on"
hide_entity: false
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_boolean.curtain_ezra
  from: 'off'
  to: 'on'
action:
  service: cover.close_cover
  entity_id: cover.curtain_mbr
