alias: "[Curtain] Downstairs boolean off"
hide_entity: false
initial_state: 'on'
trigger:
  platform: state
  entity_id: input_boolean.curtain_downstairs
  from: 'on'
  to: 'off'
action:
  service: cover.open_cover
  entity_id: cover.curtain_downstairs
