alias: Indirect Dinner Table 1/2
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: light.dt
  from: 'off'
  to: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: switch.dinner
