alias: Indirect Livingroom 2/2
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: light.livingroom_sw
  from: 'on'
  to: 'off'
action:
  - service: homeassistant.turn_off
    entity_id: switch.livingroom_light, light.livingroom_led
