alias: Indirect UP/Downstairs 4/4
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: light.first_floor
  from: 'off'
  to: 'on'
action:
  - service: homeassistant.turn_on
    entity_id: light.second_hall
