alias: Indirect UP/Downstairs 2/4
hide_entity: true
initial_state: 'on'
trigger:
- platform: state
  entity_id: light.second_hall
  from: 'on'
  to: 'off'
action:
  - service: homeassistant.turn_off
    entity_id: light.first_floor
