---
# 
# These are domain specific services which are not already covered by the 
# main components
# 
set_hold_time:
  description: 'Sets the time to hold until'
  fields:
    entity_id:
      description: Name(s) of entities to change
      example: 'climate.kitchen'
    time:
      description: Time to hold until
      example: '15:30'
