alias: "[Light on] Closet light on when door opens"
hide_entity: false
initial_state: 'on'
trigger:
- platform: state
  entity_id: binary_sensor.kast_door
  to: 'on'
action:
- service: homeassistant.turn_on
  entity_id: light.closet
- service: timer.cancel
  data:
    entity_id: timer.closet
- service: timer.start
  data:
    entity_id: timer.closet
